---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-5.9
- name: centos-6.4
- name: debian-7.1.0
- name: fedora-19
  driver_config:
    box: opscode-fedora-19
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode-fedora-19_provisionerless.box
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: ubuntu-13.04

suites:
- name: default
  run_list: ["recipe[the_silver_searcher]"]
  attributes: {}
