---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
- name: centos-5.10
- name: centos-6.5
- name: debian-7.2.0
- name: fedora-19
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: ubuntu-13.10

suites:
- name: debianish
  run_list:
  - recipe[the_silver_searcher]
  includes:
    - debian-7.2.0
    - ubuntu-10.04
    - ubuntu-12.04
    - ubuntu-13.10
- name: redhattish
  run_list:
  - recipe[the_silver_searcher]
  includes:
    - centos-5.10
    - centos-6.5
    - fedora-19
